# Welcome to Serverless!

service: merge-queue

# app and org for use with dashboard.serverless.com
app: probot

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    APP_ID: ${env:APP_ID}
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}

functions:
  webhooks:
    handler: main.handler
    events:
      - httpApi: '*'
