service: sqs

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.queue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn

resources:
  Resources:
    MyQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'MyQueue'
