name: Add to queue

on:
  pull_request_review_comment:
    types:
      - created

jobs:
  check-comment:
    runs-on: ubuntu-latest
    outputs:
      shouldAddToQueue: ${{ steps.fc.outputs.comment-id }}
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{github.event.number}}
          body-includes: /mergeit
          direction: last

  add-to-queue:
    runs-on: ubuntu-latest
    needs: check-comment
    if: ${{ check-comment.outputs.shouldAddToQueue }}
    steps:
      - uses: actions/checkout@v2

      - run: yarn

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: custom-action
        uses: ./.github/actions/add-to-queue
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRID: ${{github.event.number}}
