name: Add to queue

on:
  check_suite:
    types:
      - completed
  pull_request_review:
    types:
      - submitted

jobs:
  add-to-queue:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Added to queue"
